#!/usr/bin/env python3
"""
Verification script for the axisymmetric furnace test.

Reference data in data/ was generated by a previous GROOT run on a
200x100 cell grid (very_old_groot).  The files have no comment header.

Checks
------
  source_j25.dat    volumetric source at r ≈ 25 % R  → ref_source25.dat
  source_j75.dat    volumetric source at r ≈ 75 % R  → ref_source75.dat
  heatflux_lat.dat  lateral wall heat flux vs x       → ref_sourceqw.dat

Usage
-----
  python verify.py              # no plot window
  python verify.py --plot
"""

import argparse
import sys
import os
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

# ── Matplotlib: transparent SVG, theme-aware text ──────────────────────────
mpl.rcParams.update({
    "figure.facecolor": "none",
    "axes.facecolor":   "none",
    "savefig.facecolor":"none",
    "svg.fonttype":     "none",
})

# ── CLI ────────────────────────────────────────────────────────────────────
parser = argparse.ArgumentParser(description="Verify furnace-source test")
parser.add_argument("--plot", action="store_true",
                    help="Show interactive plot window")
args = parser.parse_args()

output_dir  = "OUTPUT"
folder_name = os.path.basename(os.getcwd())

# ── Load data ──────────────────────────────────────────────────────────────
# Reference files have no header (plain space-separated columns)
ref_s25 = np.loadtxt("data/ref_source25.dat")
ref_s75 = np.loadtxt("data/ref_source75.dat")
ref_qw  = np.loadtxt("data/ref_sourceqw.dat")

# GROOT output files have a "# ..." comment header
out_s25 = np.loadtxt(f"{output_dir}/source_j25.dat",   comments="#")
out_s75 = np.loadtxt(f"{output_dir}/source_j75.dat",   comments="#")
out_qw  = np.loadtxt(f"{output_dir}/heatflux_lat.dat", comments="#")

x_rs25, s_ref25 = ref_s25[:,0], ref_s25[:,1]
x_rs75, s_ref75 = ref_s75[:,0], ref_s75[:,1]
x_rqw,  q_ref   = ref_qw[:,0],  ref_qw[:,1]

x_s25, s_out25 = out_s25[:,0], out_s25[:,1]
x_s75, s_out75 = out_s75[:,0], out_s75[:,1]
x_qw,  q_out   = out_qw[:,0],  out_qw[:,1]

# Interpolate GROOT output at the (coarser) reference x positions
s25_at_ref = np.interp(x_rs25, x_s25, s_out25)
s75_at_ref = np.interp(x_rs75, x_s75, s_out75)
qw_at_ref  = np.interp(x_rqw,  x_qw,  q_out)

# ── Plot ───────────────────────────────────────────────────────────────────
fig, axs = plt.subplots(1, 3, figsize=(14, 4))
fig.suptitle("Axisymmetric furnace  —  non-uniform T field")

axs[0].plot(x_rs25, s_ref25,    "k--", label="Reference")
axs[0].plot(x_s25,  s_out25,    "r-",  label="GROOT")
axs[0].set_xlabel("x  [m]")
axs[0].set_ylabel("Source  [W m⁻³]")
axs[0].set_title("Source  r ≈ 25 % R")
axs[0].legend()
axs[0].grid(True, alpha=0.3)

axs[1].plot(x_rs75, s_ref75,    "k--", label="Reference")
axs[1].plot(x_s75,  s_out75,    "r-",  label="GROOT")
axs[1].set_xlabel("x  [m]")
axs[1].set_ylabel("Source  [W m⁻³]")
axs[1].set_title("Source  r ≈ 75 % R")
axs[1].legend()
axs[1].grid(True, alpha=0.3)

axs[2].plot(x_rqw,  q_ref,      "k--", label="Reference")
axs[2].plot(x_qw,   q_out,      "r-",  label="GROOT")
axs[2].set_xlabel("x  [m]")
axs[2].set_ylabel("Wall heat flux  [W m⁻²]")
axs[2].set_title("Lateral wall heat flux")
axs[2].legend()
axs[2].grid(True, alpha=0.3)

plt.tight_layout()
svg_path = os.path.join(output_dir, f"{folder_name}.svg")
png_path = os.path.join(output_dir, f"{folder_name}.png")
plt.savefig(svg_path, bbox_inches="tight", transparent=True)
plt.savefig(png_path, dpi=150, bbox_inches="tight")
print(f"Plot saved: {svg_path}, {png_path}")

if args.plot:
    plt.show()

# ── Error check ────────────────────────────────────────────────────────────
# Looser threshold: reference is from a different (older) GROOT run with
# different grid resolution and angular quadrature.
THRESHOLD = 15.0   # max relative error [%]

err_s25 = np.max(np.abs((s25_at_ref - s_ref25) / (np.abs(s_ref25) + 1e-30))) * 100.0
err_s75 = np.max(np.abs((s75_at_ref - s_ref75) / (np.abs(s_ref75) + 1e-30))) * 100.0
err_qw  = np.max(np.abs((qw_at_ref  - q_ref)   / (np.abs(q_ref)   + 1e-30))) * 100.0

print(f"Max relative error — source j25  : {err_s25:.2f} %  (threshold {THRESHOLD} %)")
print(f"Max relative error — source j75  : {err_s75:.2f} %  (threshold {THRESHOLD} %)")
print(f"Max relative error — lateral q   : {err_qw:.2f} %  (threshold {THRESHOLD} %)")

failed = False
for label, err in [("source j25", err_s25), ("source j75", err_s75), ("lateral q", err_qw)]:
    if err > THRESHOLD:
        print(f"FAIL: {label} error {err:.2f}% exceeds {THRESHOLD}%")
        failed = True

if failed:
    sys.exit(1)

print("PASS")
