!! ============================================================
!! Axisymmetric finite cylinder radiative transfer test.
!!
!! Geometry : radius R=1 m, full axial length L=2 m.
!!            Modelled as a thin wedge: δθ=0.01 rad, Nk=1.
!!            Ni_ax x Nj_rad x 1 cells.
!!
!! Medium   : uniform T=3500 K, absorption coeff k=k_user.
!!            No scattering.
!! BCs      :
!!   Face 1 (x=0)    → black wall  (bc=301, Tw=0, eps=1)
!!   Face 2 (x=L)    → black wall  (bc=301, Tw=0, eps=1)
!!   Face 3 (r=0)    → axis        (bc=300, specular)
!!   Face 4 (r=R)    → black wall  (bc=301, Tw=0, eps=1)
!!   Face 5,6 (azim) → periodic    (bc=300)
!!
!! Outputs :
!!   OUTPUT/source_axis_k{k}.dat      source term at r=0 vs x [W/m³]
!!   OUTPUT/heatflux_lateral_k{k}.dat lateral wall heat flux vs x [W/m²]
!!
!! Reference : data/ref_qwall_k*.dat  data/ref_source_axis_k*.dat
!!             (generated by cylinder.py, replacing old sol_exact.m)
!! ============================================================
program cylinder_test
  use iso_fortran_env, only: I4 => int32, R8 => real64
#if defined (_OPENMP)
  use omp_lib
#endif
  use GROOT_Config_Types_m,    only: obj_dtm, obj_rad_model, obj_io, obj_sim_param
  use GROOT_Assign_Setup,      only: Assign_Setup
  use GROOT_Advanced_Types_m,  only: GROOT_simulation_type
  use GROOT_Global_m
  use GROOT_Mod_Allocate_Data, only: Setup_Data_Structure
  use GROOT_Mod_Metrics,       only: Setup_Metrics
  use GROOT_Wrap_Solve,        only: GROOT_solve
  use Lib_ORION_Data

  implicit none

  !! Mesh parameters
  integer,  parameter :: Ni_ax  = 40   !< axial  cells
  integer,  parameter :: Nj_rad = 20   !< radial cells
  real(R8), parameter :: R_cyl  = 1.0_R8   !< cylinder radius   [m]
  real(R8), parameter :: L_cyl  = 2.0_R8   !< cylinder length   [m]
  real(R8), parameter :: T_gas  = 3500.0_R8 !< gas temperature  [K]
  real(R8), parameter :: dth    = 0.01_R8   !< wedge angle      [rad]

  type(GROOT_simulation_type) :: simulation
  type(orion_data)             :: IOgas
  real(R8) :: t1, t2

  !! --------------------------------------------------------
  !! Thread detection
#if defined (_OPENMP)
  !$omp parallel
  obj_sim_param%nthreads = OMP_GET_NUM_THREADS()
  !$omp end parallel
  write(*,'(A)')    ' Parallel execution (OpenMP)'
  write(*,'(A,I4)') '   Threads: ', obj_sim_param%nthreads
#else
  obj_sim_param%nthreads = 1
  write(*,'(A)') ' Serial execution'
#endif

  !! --------------------------------------------------------
  !! Configure (2-D axisymmetric DTM)
  obj_dtm%Nr             = 256
  obj_dtm%tol            = 1.0e-3_R8
  obj_dtm%itermax        = 1
  obj_dtm%source         = .true.
  obj_dtm%twoDax         = .true.
  obj_dtm%wedge_angle_deg= dth * 180.0_R8 / (4.0_R8 * datan(1.0_R8))
  obj_dtm%optically_thin = .false.

  obj_rad_model%model    = 'const'
  obj_rad_model%eps_wall = 1.0_R8
  obj_rad_model%k_user   = 1.0_R8

  obj_io%sol_format = 'tecplot ascii'
  obj_io%gas_format = 'tecplot ascii'

  !! Set species manually
  nsc  = 1
  nrans   = 0
  nsoot= 0
  allocate(cfd_species(1:nsc), wm_tab(1:nsc))
  cfd_species(1) = 'N2'
  wm_tab(1)      = 28.0_R8
  nscrad = 0
  nscdat = 0
  allocate(rad_species(0), ind_species(0))

  call Assign_Setup()

  write(*,'(A)')
  write(*,'(A)') ' =============================================='
  write(*,'(A)') ' Axisymmetric finite cylinder test'
  write(*,'(A)') '   Domain  : R=1 m, L=2 m'
  write(*,'(A,I0,A,I0)') '   Mesh    : ', Ni_ax, ' x ', Nj_rad, ' x 1'
  write(*,'(A,F10.6,A)') '   Wedge   : ', dth, ' rad'
  write(*,'(A)') '   bc 1,2  : endcaps  (bc=301, Tw=0, eps=1)'
  write(*,'(A)') '   bc 3    : axis     (bc=300, specular)'
  write(*,'(A)') '   bc 4    : lat wall (bc=301, Tw=0, eps=1)'
  write(*,'(A)') '   bc 5,6  : azimuth  (bc=300, periodic)'
  write(*,'(A,I0)') '   Nr      = ', Nr
  write(*,'(A,F6.2)') '   k_user  = ', k_user
  write(*,'(A)') ' =============================================='
  write(*,'(A)')

  !! --------------------------------------------------------
  !! Build IOgas in memory: axisymmetric wedge cylinder
  call Create_IOgas(IOgas, Ni_ax, Nj_rad, R_cyl, L_cyl, T_gas)

  !! --------------------------------------------------------
  !! Allocate grid and compute mesh metrics
  call Setup_Data_Structure(simulation%domain, IOgas)
  call Setup_Metrics(simulation%domain, IOgas)

  !! --------------------------------------------------------
  !! Set BCs
  call Setup_BC(simulation%domain)

  !! --------------------------------------------------------
  !! Set radiative properties (const model)
  call Setup_Rad_Const(simulation%domain, T_gas)

  !! --------------------------------------------------------
  !! Solve
  call cpu_time(t1)
  call GROOT_solve(simulation)
  call cpu_time(t2)

  write(*,'(A)')
  write(*,'(A,F8.4,A)') '   CPU time: ', &
    (t2-t1)/real(obj_sim_param%nthreads,R8)/60.0_R8, ' min'

  !! --------------------------------------------------------
  call Write_Output(simulation%domain, Ni_ax, L_cyl)

  write(*,'(A)') ' Done. See OUTPUT/source_axis_k*.dat and OUTPUT/heatflux_lateral_k*.dat'
  write(*,'(A)')

contains

  !! ----------------------------------------------------------
  !! Build axisymmetric wedge cylinder mesh.
  !!   i-direction : axial   (x), 0 to L_cyl
  !!   j-direction : radial  (y projected), 0 to R_cyl
  !!   k-direction : azimuth (z projected), Nk=1
  !!
  !! Node coordinates:
  !!   mesh(1) = x  = i * L_cyl / Ni
  !!   mesh(2) = y  = r * cos(dth/2)
  !!   mesh(3) = z  = ±r * sin(dth/2)   (k=0 → minus, k=1 → plus)
  !!
  !! Axis nodes use r_min=1e-6 to avoid degenerate cells.
  subroutine Create_IOgas(IOgas, Ni, Nj, R0, L0, T0)
    implicit none
    type(orion_data), intent(out) :: IOgas
    integer,  intent(in) :: Ni, Nj
    real(R8), intent(in) :: R0, L0, T0
    integer  :: i, j, k
    real(R8) :: p0, R_air, rho, rr, cdth, sdth
    real(R8), parameter :: r_min = 1.0e-6_R8

    p0    = 1.0e5_R8
    R_air = 287.0_R8
    rho   = p0 / (R_air * T0)
    cdth  = cos(dth * 0.5_R8)
    sdth  = sin(dth * 0.5_R8)

    allocate(IOgas%block(1))
    IOgas%block(1)%Ni   = Ni
    IOgas%block(1)%Nj   = Nj
    IOgas%block(1)%Nk   = 1
    IOgas%block(1)%name = 'Block1'

    allocate(IOgas%block(1)%mesh(1:3, 0:Ni, 0:Nj, 0:1))
    allocate(IOgas%block(1)%vars(1:8, 1:Ni, 1:Nj, 1:1))

    !! Wedge mesh nodes
    do k = 0, 1; do j = 0, Nj; do i = 0, Ni
      rr = max(real(j,R8) * R0 / real(Nj,R8), r_min)
      IOgas%block(1)%mesh(1, i, j, k) = real(i,R8) * L0 / real(Ni,R8)
      IOgas%block(1)%mesh(2, i, j, k) = rr * cdth
      IOgas%block(1)%mesh(3, i, j, k) = rr * sdth * real(2*k - 1, R8)
    end do; end do; end do

    !! Uniform field
    do k = 1, 1; do j = 1, Nj; do i = 1, Ni
      IOgas%block(1)%vars(1, i, j, k) = rho
      IOgas%block(1)%vars(2, i, j, k) = 0.0_R8
      IOgas%block(1)%vars(3, i, j, k) = 0.0_R8
      IOgas%block(1)%vars(4, i, j, k) = 0.0_R8
      IOgas%block(1)%vars(5, i, j, k) = p0
      IOgas%block(1)%vars(6, i, j, k) = T0
      IOgas%block(1)%vars(7, i, j, k) = 1.4_R8
      IOgas%block(1)%vars(8, i, j, k) = R_air
    end do; end do; end do
  end subroutine Create_IOgas


  !! ----------------------------------------------------------
  !! Set boundary conditions:
  !!   Face 1 (x=0)   : bc=301, black wall
  !!   Face 2 (x=L)   : bc=301, black wall
  !!   Face 3 (r=0)   : bc=300, specular (axis)
  !!   Face 4 (r=R)   : bc=301, black wall (lateral)
  !!   Face 5,6 (azim): bc=300, periodic
  subroutine Setup_BC(grid)
    use GROOT_Advanced_Types_m, only: GROOT_domain_type
    implicit none
    type(GROOT_domain_type), intent(inout) :: grid
    integer :: b, ifa

    do b = 1, grid%nb
      do ifa = 1, 6
        !! Initialise flux and weight arrays on all faces
        grid%blk(b)%face(ifa)%Q   (:,:,:) = 0.0_R8
        grid%blk(b)%face(ifa)%Qtot(:,:)   = 0.0_R8
        grid%blk(b)%face(ifa)%a   (:,:,:) = 1.0_R8
      end do

      !! Endcap at x=0
      grid%blk(b)%face(1)%bc (:,:) = 301
      grid%blk(b)%face(1)%T  (:,:) = 0.0_R8
      grid%blk(b)%face(1)%eps(:,:) = 1.0_R8

      !! Endcap at x=L
      grid%blk(b)%face(2)%bc (:,:) = 301
      grid%blk(b)%face(2)%T  (:,:) = 0.0_R8
      grid%blk(b)%face(2)%eps(:,:) = 1.0_R8

      !! Axis (r=0) — specular reflection
      grid%blk(b)%face(3)%bc (:,:) = 300
      grid%blk(b)%face(3)%T  (:,:) = 0.0_R8
      grid%blk(b)%face(3)%eps(:,:) = 0.0_R8

      !! Lateral wall (r=R)
      grid%blk(b)%face(4)%bc (:,:) = 301
      grid%blk(b)%face(4)%T  (:,:) = 0.0_R8
      grid%blk(b)%face(4)%eps(:,:) = 1.0_R8

      !! Azimuthal faces — periodic/axisymmetric
      grid%blk(b)%face(5)%bc (:,:) = 200
      grid%blk(b)%face(5)%T  (:,:) = 0.0_R8
      grid%blk(b)%face(5)%eps(:,:) = 0.0_R8

      grid%blk(b)%face(6)%bc (:,:) = 200
      grid%blk(b)%face(6)%T  (:,:) = 0.0_R8
      grid%blk(b)%face(6)%eps(:,:) = 0.0_R8
    end do
  end subroutine Setup_BC


  !! ----------------------------------------------------------
  subroutine Setup_Rad_Const(grid, T0)
    use GROOT_Advanced_Types_m, only: GROOT_domain_type
    implicit none
    type(GROOT_domain_type), intent(inout) :: grid
    real(R8), intent(in) :: T0
    integer :: b, Nx, Ny, Nz
    real(R8) :: Ib_val

    Ib_val = sigma * T0**4 / pi

    do b = 1, grid%nb
      Nx = grid%blk(b)%dim(1)
      Ny = grid%blk(b)%dim(2)
      Nz = grid%blk(b)%dim(3)

      allocate(grid%blk(b)%ka    (1:Nx, 1:Ny, 1:Nz, 0:Ngg))
      allocate(grid%blk(b)%a     (1:Nx, 1:Ny, 1:Nz, 0:Ngg))
      allocate(grid%blk(b)%Ib    (1:Nx, 1:Ny, 1:Nz))
      allocate(grid%blk(b)%source(1:Nx, 1:Ny, 1:Nz))
      allocate(grid%blk(b)%G     (1:Nx, 1:Ny, 1:Nz))

      grid%blk(b)%ka    (:,:,:,:) = k_user
      grid%blk(b)%a     (:,:,:,:) = 1.0_R8
      grid%blk(b)%Ib    (:,:,:)   = Ib_val
      grid%blk(b)%source(:,:,:)   = 0.0_R8
      grid%blk(b)%G     (:,:,:)   = 0.0_R8
    end do
  end subroutine Setup_Rad_Const


  !! ----------------------------------------------------------
  !! Write source term on axis (j=1) and lateral wall heat flux
  !! (face 4, r=R) vs axial position x.
  !! File names include the absorption coefficient, e.g. source_axis_k1.dat
  subroutine Write_Output(grid, Ni, L0)
    use GROOT_Advanced_Types_m, only: GROOT_domain_type
    implicit none
    type(GROOT_domain_type), intent(in) :: grid
    integer,  intent(in) :: Ni
    real(R8), intent(in) :: L0
    integer :: b, i, unit1, unit2
    real(R8) :: dx, x
    character(len=8) :: k_str

    !! Build k label: 0.1 → "0.1", 1.0 → "1", 10.0 → "10"
    if (abs(k_user - 0.1_R8) < 1.0e-6_R8) then
      k_str = '0.1'
    elseif (abs(k_user - 10.0_R8) < 1.0e-6_R8) then
      k_str = '10'
    else
      k_str = '1'
    end if

    b  = 1
    dx = L0 / real(Ni, R8)

    call execute_command_line('mkdir -p OUTPUT', wait=.true.)
    open(newunit=unit1, file='OUTPUT/source_axis_k'//trim(k_str)//'.dat')
    write(unit1,'(A)') '# x [m]              source [W/m3]   (axis, r=0)'
    do i = 1, Ni
      x = (real(i,R8) - 0.5_R8) * dx
      write(unit1,'(2ES20.8)') x, grid%blk(b)%source(i, 1, 1)
    end do
    close(unit1)

    open(newunit=unit2, file='OUTPUT/heatflux_lateral_k'//trim(k_str)//'.dat')
    write(unit2,'(A)') '# x [m]              Qtot [W/m2]     (lateral wall, r=R)'
    do i = 1, Ni
      x = (real(i,R8) - 0.5_R8) * dx
      write(unit2,'(2ES20.8)') x, grid%blk(b)%face(4)%Qtot(i, 1)
    end do
    close(unit2)
  end subroutine Write_Output

end program cylinder_test
