#!/usr/bin/env python3
"""
Verification script for the axisymmetric finite-cylinder test.

Reference data in data/ was generated by data/cylinder.py (analytical
integration via scipy) for a uniform-temperature grey cylinder
(R=1 m, L=2 m, T=3500 K, black walls).

Checks
------
  heatflux_lateral.dat   lateral wall heat flux vs x   → ref_qwall_k{k}.dat
  source_axis.dat        on-axis source term vs x       → ref_source_axis_k{k}.dat

Usage
-----
  python verify.py              # k=1.0, no plot window
  python verify.py --k 0.1
  python verify.py --k 10 --plot
"""

import argparse
import sys
import os
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

# ── Matplotlib: transparent SVG, theme-aware text ──────────────────────────
mpl.rcParams.update({
    "figure.facecolor": "none",
    "axes.facecolor":   "none",
    "savefig.facecolor":"none",
    "svg.fonttype":     "none",
})

# ── CLI ────────────────────────────────────────────────────────────────────
parser = argparse.ArgumentParser(description="Verify finite-cylinder test")
parser.add_argument("--k",    type=float, default=1.0,
                    choices=[0.1, 1.0, 10.0],
                    help="Absorption coefficient used in the run (default: 1.0)")
parser.add_argument("--plot", action="store_true",
                    help="Show interactive plot window")
args = parser.parse_args()

k     = args.k
k_lbl = f"{k:g}"
output_dir  = "OUTPUT"
folder_name = os.path.basename(os.getcwd())

# ── Load data ──────────────────────────────────────────────────────────────
def load_dat(path):
    return np.loadtxt(path, comments="#")

ref_qw  = load_dat(f"data/ref_qwall_k{k_lbl}.dat")
ref_src = load_dat(f"data/ref_source_axis_k{k_lbl}.dat")
out_qw  = load_dat(f"{output_dir}/heatflux_lateral_k{k_lbl}.dat")
out_src = load_dat(f"{output_dir}/source_axis_k{k_lbl}.dat")

x_ref_qw,  q_ref  = ref_qw[:,0],  ref_qw[:,1]
x_ref_src, s_ref  = ref_src[:,0], ref_src[:,1]
x_qw,      q_out  = out_qw[:,0],  out_qw[:,1]
x_src,     s_out  = out_src[:,0], out_src[:,1]

# Interpolate reference onto GROOT output grid
q_ref_i = np.interp(x_qw,  x_ref_qw,  q_ref)
s_ref_i = np.interp(x_src, x_ref_src, s_ref)

# ── Plot ───────────────────────────────────────────────────────────────────
fig, axs = plt.subplots(1, 2, figsize=(10, 4))
fig.suptitle(f"Finite cylinder  —  k = {k_lbl} m⁻¹,  T = 3500 K")

axs[0].plot(x_ref_qw,  q_ref,  "k--", label="Reference (analytical)")
axs[0].plot(x_qw,      q_out,  "r-",  label="GROOT")
axs[0].set_xlabel("x  [m]")
axs[0].set_ylabel("Lateral wall heat flux  [W m⁻²]")
axs[0].set_title("Lateral wall heat flux")
axs[0].legend()
axs[0].grid(True, alpha=0.3)

axs[1].plot(x_ref_src, s_ref,  "k--", label="Reference (analytical)")
axs[1].plot(x_src,     s_out,  "r-",  label="GROOT")
axs[1].set_xlabel("x  [m]")
axs[1].set_ylabel("Source term  [W m⁻³]")
axs[1].set_title("On-axis source term")
axs[1].legend()
axs[1].grid(True, alpha=0.3)

plt.tight_layout()
svg_path = os.path.join(output_dir, f"{folder_name}_k{k_lbl}.svg")
png_path = os.path.join(output_dir, f"{folder_name}_k{k_lbl}.png")
plt.savefig(svg_path, bbox_inches="tight", transparent=True)
plt.savefig(png_path, dpi=150, bbox_inches="tight")
print(f"Plot saved: {svg_path}, {png_path}")

if args.plot:
    plt.show()

# ── Error check ────────────────────────────────────────────────────────────
THRESHOLD = 5.0   # max relative error [%]

err_qw  = np.max(np.abs((q_out - q_ref_i) / (np.abs(q_ref_i) + 1e-30))) * 100.0
err_src = np.max(np.abs((s_out - s_ref_i) / (np.abs(s_ref_i) + 1e-30))) * 100.0

print(f"Max relative error — lateral heat flux : {err_qw:.2f} %  (threshold {THRESHOLD} %)")
print(f"Max relative error — axis source       : {err_src:.2f} %  (threshold {THRESHOLD} %)")

failed = False
if err_qw > THRESHOLD:
    print(f"FAIL: lateral heat flux error {err_qw:.2f}% exceeds {THRESHOLD}%")
    failed = True
if err_src > THRESHOLD:
    print(f"FAIL: axis source error {err_src:.2f}% exceeds {THRESHOLD}%")
    failed = True

if failed:
    sys.exit(1)

print("PASS")
